# Site settings
title: ULF SCHNEIDER
# email: mail@ulf.codes
phone: +49 163 2505164
description: Developer â€¢ Agile Coach
meta: Ulf Schneider Agile Paderborn
baseurl:  # the subpath of your site, e.g. /blog/
name: Ulf Schneider
url: http://ulf.codes # the base hostname & protocol for thesite
twitter_username: ulfeed
#github_username:
#twoople_username:


# Build settings
markdown: kramdown
include: ['_pages']
permalink: '/:title/'
